In [2]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

교수님 안녕하세요


In [3]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [4]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [5]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [7]:
arVal[1][2]

3.14

In [8]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [9]:
arVal[0][2]

't'

In [10]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [11]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [12]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [13]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [14]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [16]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [17]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [18]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [19]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [20]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [21]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [22]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [23]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [25]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [26]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [27]:
pandas_series[0]

30

In [28]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [29]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [30]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [31]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [32]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [33]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [34]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [35]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [36]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [37]:
# column 삭제
del df['score']

In [38]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [39]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [40]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [41]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [42]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0 -0.443330  0.446551  0.643977 -0.624363 -0.322337
1  0.518619  0.265923  0.743022 -1.348812 -0.154473
2 -0.372443  0.224063  1.306512 -0.727279 -0.577286
3 -0.298748 -0.253664  1.078971 -1.521560 -1.747715
4  1.265987 -0.207989 -0.951082 -0.151919 -1.090570

In [43]:
# 최대값
df.max()

A    1.265987
B    0.446551
C    1.306512
D   -0.151919
E   -0.154473
dtype: float64

In [44]:
# 최소값
df.min()

A   -0.443330
B   -0.253664
C   -0.951082
D   -1.521560
E   -1.747715
dtype: float64

In [45]:
# 평균
df.mean()

A    0.134017
B    0.094977
C    0.564280
D   -0.874786
E   -0.778476
dtype: float64

In [46]:
# 표준편차
df.std()

A    0.742696
B    0.309366
C    0.887473
D    0.559022
E    0.647060
dtype: float64

In [47]:
# 누적값
df.cumsum()

A         B         C         D         E
0 -0.443330  0.446551  0.643977 -0.624363 -0.322337
1  0.075288  0.712474  1.386999 -1.973175 -0.476809
2 -0.297154  0.936537  2.693511 -2.700454 -1.054095
3 -0.595903  0.682873  3.772482 -4.222013 -2.801810
4  0.670084  0.474884  2.821400 -4.373932 -3.892380

In [48]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.134017  0.094977  0.564280 -0.874786 -0.778476
std    0.742696  0.309366  0.887473  0.559022  0.647060
min   -0.443330 -0.253664 -0.951082 -1.521560 -1.747715
25%   -0.372443 -0.207989  0.643977 -1.348812 -1.090570
50%   -0.298748  0.224063  0.743022 -0.727279 -0.577286
75%    0.518619  0.265923  1.078971 -0.624363 -0.322337
max    1.265987  0.446551  1.306512 -0.151919 -0.154473

In [49]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.443330  0.446551  0.643977 -0.624363 -0.322337        X
1  0.518619  0.265923  0.743022 -1.348812 -0.154473        Y
2 -0.372443  0.224063  1.306512 -0.727279 -0.577286        X
3 -0.298748 -0.253664  1.078971 -1.521560 -1.747715        Y
4  1.265987 -0.207989 -0.951082 -0.151919 -1.090570        Z

In [50]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.407887  0.335307  0.975245 -0.675821 -0.449811
Y         0.109935  0.006130  0.910996 -1.435186 -0.951094
Z         1.265987 -0.207989 -0.951082 -0.151919 -1.090570